import { IScannedFile } from '../scanner/interfaces';

import { createCandidatePairs, type IPathPair } from './dedupe-candidate-pairs';
import {
  appendIndexToRoot,
  buildDedupeResult,
  buildDuplicateGroup,
  buildReportActionOutcome,
  buildReplaceActionOutcome,
  buildSkipActionOutcome,
  buildStrategyExecution,
  createGroupIndexPairs,
  createInitialParents,
  createPairId,
  createPairMatchMap,
  getGroupFiles,
  getSuccessfulCandidates,
  getSuccessfulExecutions,
  getSupportedFiles,
  replaceParent,
  type IIndexPair,
  type IStrategyExecution,
  type IStrategyMatch
} from './dedupe-service.helpers';
import { isDuplicateGroup, isDuplicatePairEvaluation, toFileIndexEntry, type IDuplicatePairEvaluation } from './dedupe-service.shared';
import { IDedupeService, IDedupeStrategy } from './interfaces';
import {
  DedupeAction,
  DedupeMode,
  IDedupeCandidate,
  IDedupeOutcome,
  IDedupeResult,
  IDuplicateGroup
} from './types';

interface IPairMatchResult { readonly applicableStrategies: number; readonly matched: readonly IStrategyMatch[]; }

const MIN_DUPLICATE_GROUP_SIZE = 2;

/**
 * Main dedupe orchestration service.
 * Coordinates multiple strategies to find and handle duplicate files.
 */
export class DedupeService implements IDedupeService {
  /**
   * Creates a new DedupeService instance
   * @param strategies - Array of deduplication strategies to use for finding duplicates
   * @param mode - Composition mode for combining strategy matches
   */
  constructor(
    private readonly strategies: readonly IDedupeStrategy[],
    private readonly mode: Readonly<DedupeMode> = DedupeMode.ANY
  ) {}

  /**
   * Finds duplicate files using all configured strategies.
   * Compares files pairwise so strategy composition mode is honored consistently.
   * @param files - Array of scanned files to analyze for duplicates
   * @returns Dedupe result containing groups of duplicates and metadata about the analysis
   */
  async findDuplicates(files: readonly IScannedFile[]): Promise<IDedupeResult> {
    const strategyExecutions = await this.executeStrategies(files);
    const groups = this.groupCandidates(files, strategyExecutions);
    return buildDedupeResult(files.length, groups, strategyExecutions);
  }

  /**
   * Applies the configured action to duplicate groups.
   * Currently supports SKIP, REPORT, and REPLACE actions.
   * Async for future extensibility (e.g., REPLACE action may need file operations).
   * @param result - Dedupe result containing duplicate groups to process
   * @param action - Action to apply to the duplicate groups (SKIP, REPORT, or REPLACE)
   * @returns Dedupe outcome with details about the action applied
   * @throws {Error} Thrown when an unsupported dedupe action is requested.
   */
  applyAction(
    result: Readonly<IDedupeResult>,
    action: Readonly<DedupeAction>
  ): Promise<IDedupeOutcome> {
    switch (action) {
      case DedupeAction.SKIP:
        return Promise.resolve(buildSkipActionOutcome(result));
      case DedupeAction.REPORT:
        return Promise.resolve(buildReportActionOutcome(result));
      case DedupeAction.REPLACE:
        return Promise.resolve(buildReplaceActionOutcome(result));
      default:
        return Promise.reject(new Error(`Unsupported dedupe action: ${String(action)}`));
    }
  }

  /**
   * Executes a single strategy on all files and returns candidates.
   * Only processes files supported by the strategy and filters out null keys.
   * @param strategy - Deduplication strategy to execute
   * @param files - Array of scanned files to process with the strategy
   * @returns Array of dedupe candidates generated by the strategy
   */
  private async executeStrategies(
    files: readonly IScannedFile[]
  ): Promise<readonly IStrategyExecution[]> {
    const executionPromises = this.createStrategyExecutionPromises(files);
    const executions = await Promise.all(executionPromises);
    return getSuccessfulExecutions(executions);
  }

  /**
   * Creates strategy execution promises for parallel evaluation.
   * @param files - Scanned files to evaluate.
   * @returns Strategy execution promises.
   */
  private createStrategyExecutionPromises(
    files: readonly IScannedFile[]
  ): readonly Promise<IStrategyExecution | null>[] {
    return this.strategies.map(this.createStrategyExecutionPromise.bind(this, files));
  }

  /**
   * Creates one strategy execution promise.
   * @param files - Files to evaluate.
   * @param strategy - Strategy being executed.
   * @returns Strategy execution promise.
   */
  private createStrategyExecutionPromise(
    files: readonly IScannedFile[],
    strategy: Readonly<IDedupeStrategy>
  ): Promise<IStrategyExecution | null> {
    return this.executeSingleStrategy(strategy, files);
  }

  /**
   * Executes one strategy and converts its candidates into keyed lookup data.
   * @param strategy - Deduplication strategy to execute.
   * @param files - Files to process with the strategy.
   * @returns Strategy execution metadata or null when no candidates were produced.
   */
  private async executeSingleStrategy(
    strategy: Readonly<IDedupeStrategy>,
    files: readonly IScannedFile[]
  ): Promise<IStrategyExecution | null> {
    const candidates = await this.executeStrategy(strategy, files);
    return candidates.length === 0 ? null : buildStrategyExecution(strategy.name, candidates);
  }

  /**
   * Executes a single strategy against supported files in parallel.
   * @param strategy - Deduplication strategy to execute.
   * @param files - Files to process with the strategy.
   * @returns Dedupe candidates generated by the strategy.
   */
  private async executeStrategy(
    strategy: Readonly<IDedupeStrategy>,
    files: readonly IScannedFile[]
  ): Promise<IDedupeCandidate[]> {
    const supportedFiles = getSupportedFiles(strategy, files);
    const candidateResults = await Promise.all(
      this.createCandidatePromises(strategy, supportedFiles)
    );
    return getSuccessfulCandidates(candidateResults);
  }

  /**
   * Creates candidate promises for each supported file.
   * @param strategy - Deduplication strategy to execute.
   * @param supportedFiles - Files supported by the strategy.
   * @returns Candidate promises.
   */
  private createCandidatePromises(
    strategy: Readonly<IDedupeStrategy>,
    supportedFiles: readonly IScannedFile[]
  ): readonly Promise<IDedupeCandidate | null>[] {
    return supportedFiles.map(this.createCandidatePromise.bind(this, strategy));
  }

  /**
   * Creates one candidate promise for a supported file.
   * @param strategy - Deduplication strategy to execute.
   * @param file - File being evaluated.
   * @returns Candidate promise.
   */
  private createCandidatePromise(
    strategy: Readonly<IDedupeStrategy>,
    file: Readonly<IScannedFile>
  ): Promise<IDedupeCandidate | null> {
    return this.createCandidate(strategy, file);
  }

  /**
   * Creates a candidate for one file and strategy when a key is available.
   * @param strategy - Deduplication strategy to execute.
   * @param file - File being evaluated.
   * @returns Dedupe candidate or null when no key was produced.
   */
  private async createCandidate(
    strategy: Readonly<IDedupeStrategy>,
    file: Readonly<IScannedFile>
  ): Promise<IDedupeCandidate | null> {
    const key = await strategy.getKey(file);
    return key === null ? null : { file, key, strategy: strategy.name };
  }

  /**
   * Groups files by pairwise duplicate relationships derived from configured strategies.
   * @param files - Files being analyzed for duplicates.
   * @param strategyExecutions - Strategy outputs keyed by file path.
   * @returns Duplicate groups with multiple files per group.
   */
  private groupCandidates(
    files: readonly IScannedFile[],
    strategyExecutions: readonly IStrategyExecution[]
  ): IDuplicateGroup[] {
    if (files.length < MIN_DUPLICATE_GROUP_SIZE || strategyExecutions.length === 0) {
      return [];
    }

    const pairEvaluations = this.createDuplicatePairEvaluations(files, strategyExecutions);
    const parents = this.createParentsFromPairs(files.length, pairEvaluations);
    const pairMatches = createPairMatchMap(pairEvaluations);
    return this.buildGroups(files, parents, pairMatches);
  }

  /**
   * Creates duplicate-pair evaluations for all file pairs.
   * @param files - Files being analyzed for duplicates.
   * @param strategyExecutions - Strategy outputs keyed by file path.
   * @returns Duplicate pair evaluations that satisfied the configured mode.
   */
  private createDuplicatePairEvaluations(
    files: readonly IScannedFile[],
    strategyExecutions: readonly IStrategyExecution[]
  ): readonly IDuplicatePairEvaluation[] {
    const fileIndexesByPath = this.createFileIndexesByPath(files);
    return createCandidatePairs(strategyExecutions)
      .map(this.evaluateCandidatePair.bind(this, files, fileIndexesByPath, strategyExecutions))
      .filter(isDuplicatePairEvaluation);
  }

  /**
   * Creates file-index lookup data keyed by original path.
   * @param files - Files being analyzed for duplicates.
   * @returns File-index lookup map.
   */
  private createFileIndexesByPath(files: readonly IScannedFile[]): ReadonlyMap<string, number> {
    return new Map(files.map(toFileIndexEntry));
  }

  /**
   * Evaluates one candidate file-path pair for duplicate matching.
   * @param files - Files being analyzed for duplicates.
   * @param fileIndexesByPath - File-index lookup keyed by original path.
   * @param strategyExecutions - Strategy outputs keyed by file path.
   * @param pair - Candidate file-path pair.
   * @returns Duplicate pair evaluation or null when not a duplicate.
   */
  private evaluateCandidatePair(
    files: readonly IScannedFile[],
    fileIndexesByPath: Readonly<ReadonlyMap<string, number>>,
    strategyExecutions: readonly IStrategyExecution[],
    pair: Readonly<IPathPair>
  ): IDuplicatePairEvaluation | null {
    const filePair = this.toIndexPair(pair, fileIndexesByPath);
    return filePair
      ? this.createDuplicatePairEvaluation(files, filePair, strategyExecutions)
      : null;
  }

  /**
   * Converts one file-path pair into file indexes when both paths are known.
   * @param pair - Candidate file-path pair.
   * @param fileIndexesByPath - File-index lookup keyed by original path.
   * @returns File-index pair or null when either path is unknown.
   */
  private toIndexPair(
    pair: Readonly<IPathPair>,
    fileIndexesByPath: Readonly<ReadonlyMap<string, number>>
  ): IIndexPair | null {
    const leftIndex = fileIndexesByPath.get(pair.leftPath);
    const rightIndex = fileIndexesByPath.get(pair.rightPath);
    return leftIndex === undefined || rightIndex === undefined
      ? null
      : { leftIndex, rightIndex };
  }

  /**
   * Creates one duplicate pair evaluation when the pair satisfies the configured mode.
   * @param files - Files being analyzed for duplicates.
   * @param pair - File-index pair being evaluated.
   * @param strategyExecutions - Strategy outputs keyed by file path.
   * @returns Duplicate pair evaluation or null when the pair is not a duplicate.
   */
  private createDuplicatePairEvaluation(
    files: readonly IScannedFile[],
    pair: Readonly<IIndexPair>,
    strategyExecutions: readonly IStrategyExecution[]
  ): Readonly<{
    leftIndex: number;
    matched: readonly IStrategyMatch[];
    rightIndex: number;
  }> | null {
    const matchResult = this.findPairMatches(
      files[pair.leftIndex].originalPath,
      files[pair.rightIndex].originalPath,
      strategyExecutions
    );
    return this.isDuplicatePair(matchResult.matched, matchResult.applicableStrategies)
      ? { ...pair, matched: matchResult.matched }
      : null;
  }

  /**
   * Creates parent pointers by unioning all duplicate file pairs.
   * @param fileCount - Number of files in the scan set.
   * @param pairEvaluations - Duplicate pair evaluations.
   * @returns Parent pointers for disjoint duplicate sets.
   */
  private createParentsFromPairs(
    fileCount: number,
    pairEvaluations: readonly Readonly<{
      leftIndex: number;
      rightIndex: number;
    }>[]
  ): readonly number[] {
    let parents = createInitialParents(fileCount);

    for (const pair of pairEvaluations) {
      parents = this.union(parents, pair.leftIndex, pair.rightIndex);
    }

    return parents;
  }

  /**
   * Finds matching strategy keys for a pair of files.
   * @param leftPath - First file path.
   * @param rightPath - Second file path.
   * @param strategyExecutions - Strategy outputs keyed by file path.
   * @returns Applicable strategy count and matching strategies.
   */
  private findPairMatches(
    leftPath: string,
    rightPath: string,
    strategyExecutions: readonly IStrategyExecution[]
  ): IPairMatchResult {
    let matched: readonly IStrategyMatch[] = [];
    let applicableStrategies = 0;

    for (const execution of strategyExecutions) {
      const leftKey = execution.keysByPath.get(leftPath);
      const rightKey = execution.keysByPath.get(rightPath);

      if (leftKey === undefined || rightKey === undefined) {
        continue;
      }

      applicableStrategies += 1;
      if (leftKey === rightKey) {
        matched = [...matched, { strategy: execution.strategy, key: leftKey }];
      }
    }

    return { applicableStrategies, matched };
  }

  /**
   * Determines whether a pair is duplicate under the configured composition mode.
   * @param matchedStrategies - Strategies whose keys matched for the pair
   * @param applicableStrategies - Enabled strategies that produced keys for both files
   * @returns True when the pair should be treated as duplicate
   */
  private isDuplicatePair(
    matchedStrategies: readonly IStrategyMatch[],
    applicableStrategies: number
  ): boolean {
    if (this.mode === DedupeMode.ALL) {
      return applicableStrategies > 0 && matchedStrategies.length === applicableStrategies;
    }

    return matchedStrategies.length > 0;
  }

  /**
   * Builds duplicate groups from the connected duplicate pairs.
   * @param files - Files being analyzed for duplicates
   * @param parents - Disjoint-set parent indices for each file
   * @param pairMatches - Matching strategies for each duplicate pair
   * @returns Array of duplicate groups
   */
  private buildGroups(
    files: readonly IScannedFile[],
    parents: readonly number[],
    pairMatches: Readonly<ReadonlyMap<string, readonly IStrategyMatch[]>>
  ): IDuplicateGroup[] {
    const groupedIndexes = this.groupIndexesByRoot(files.length, parents);
    return this.createDuplicateGroups(files, groupedIndexes, pairMatches);
  }

  /**
   * Groups file indexes by their resolved duplicate root.
   * @param fileCount - Number of files in the scan set.
   * @param parents - Parent pointers for duplicate sets.
   * @returns File indexes grouped by duplicate root.
   */
  private groupIndexesByRoot(
    fileCount: number,
    parents: readonly number[]
  ): readonly Readonly<{ indexes: readonly number[]; root: number }>[] {
    let groupedRoots: readonly Readonly<{ indexes: readonly number[]; root: number }>[] = [];

    for (const index of createInitialParents(fileCount)) {
      const root = this.find(parents, index);
      groupedRoots = appendIndexToRoot(groupedRoots, root, index);
    }

    return groupedRoots;
  }

  /**
   * Creates duplicate groups from grouped indexes.
   * @param files - Files being analyzed for duplicates.
   * @param groupedIndexes - File indexes grouped by duplicate root.
   * @param pairMatches - Matching strategies for each duplicate pair.
   * @returns Duplicate groups.
   */
  private createDuplicateGroups(
    files: readonly IScannedFile[],
    groupedIndexes: readonly Readonly<{ indexes: readonly number[]; root: number }>[],
    pairMatches: Readonly<ReadonlyMap<string, readonly IStrategyMatch[]>>
  ): IDuplicateGroup[] {
    return groupedIndexes
      .map(this.createDuplicateGroupFromRoot.bind(this, files, pairMatches))
      .filter(isDuplicateGroup);
  }

  /**
   * Creates one duplicate group from grouped root indexes.
   * @param files - Files being analyzed for duplicates.
   * @param pairMatches - Matching strategies for each duplicate pair.
   * @param groupedRoot - File indexes grouped by duplicate root.
   * @returns Duplicate group or null when too small.
   */
  private createDuplicateGroupFromRoot(
    files: readonly IScannedFile[],
    pairMatches: Readonly<ReadonlyMap<string, readonly IStrategyMatch[]>>,
    groupedRoot: Readonly<{ indexes: readonly number[]; root: number }>
  ): IDuplicateGroup | null {
    return this.createDuplicateGroup(files, groupedRoot.indexes, pairMatches);
  }

  /**
   * Creates one duplicate group when enough files are present.
   * @param files - Files being analyzed for duplicates.
   * @param indexes - File indexes in the duplicate group.
   * @param pairMatches - Matching strategies for each duplicate pair.
   * @returns Duplicate group or null when fewer than two files are present.
   */
  private createDuplicateGroup(
    files: readonly IScannedFile[],
    indexes: readonly number[],
    pairMatches: Readonly<ReadonlyMap<string, readonly IStrategyMatch[]>>
  ): IDuplicateGroup | null {
    if (indexes.length < MIN_DUPLICATE_GROUP_SIZE) {
      return null;
    }

    const groupFiles = getGroupFiles(files, indexes);
    const matchMetadata = this.collectGroupMatches(indexes, pairMatches);
    return buildDuplicateGroup(groupFiles, matchMetadata);
  }

  /**
   * Collects all matching strategies contributing to a duplicate group.
   * @param indexes - File indexes in the duplicate group.
   * @param pairMatches - Matching strategies for each duplicate pair.
   * @returns Strategy match metadata for the group.
   */
  private collectGroupMatches(
    indexes: readonly number[],
    pairMatches: Readonly<ReadonlyMap<string, readonly IStrategyMatch[]>>
  ): readonly IStrategyMatch[] {
    let matches: readonly IStrategyMatch[] = [];

    for (const pair of createGroupIndexPairs(indexes)) {
      const pairMatch = pairMatches.get(createPairId(pair.leftIndex, pair.rightIndex));
      if (pairMatch) {
        matches = [...matches, ...pairMatch];
      }
    }

    return matches;
  }

  /**
   * Finds the representative index for the disjoint-set structure.
   * @param parents - Parent pointers for each file index.
   * @param index - Index to resolve.
   * @returns Representative index for the set.
   */
  private find(parents: readonly number[], index: number): number {
    return parents[index] === index ? index : this.find(parents, parents[index]);
  }

  /**
   * Merges two duplicate sets in the disjoint-set structure.
   * @param parents - Parent pointers for each file index.
   * @param leftIndex - First file index.
   * @param rightIndex - Second file index.
   * @returns Updated parent pointers.
   */
  private union(
    parents: readonly number[],
    leftIndex: number,
    rightIndex: number
  ): readonly number[] {
    const leftRoot = this.find(parents, leftIndex);
    const rightRoot = this.find(parents, rightIndex);

    if (leftRoot === rightRoot) {
      return parents;
    }

    return replaceParent(parents, rightRoot, leftRoot);
  }
}
