import { IScannedFile } from '../scanner/interfaces';

import { IDedupeService, IDedupeStrategy } from './interfaces';
import {
  DedupeAction,
  DedupeMode,
  IDedupeResult,
  IDedupeOutcome,
  IDuplicateGroup,
  IDedupeCandidate
} from './types';

interface IStrategyExecution {
  readonly strategy: string;
  readonly keysByPath: ReadonlyMap<string, string>;
}

interface IStrategyMatch {
  readonly strategy: string;
  readonly key: string;
}

/**
 * Main dedupe orchestration service.
 * Coordinates multiple strategies to find and handle duplicate files.
 */
export class DedupeService implements IDedupeService {
  /**
   * Creates a new DedupeService instance
   * @param strategies - Array of deduplication strategies to use for finding duplicates
   * @param mode - Composition mode for combining strategy matches
   */
  constructor(
    private readonly strategies: readonly IDedupeStrategy[],
    private readonly mode: DedupeMode = DedupeMode.ANY
  ) {}

  /**
   * Finds duplicate files using all configured strategies.
   * Compares files pairwise so strategy composition mode is honored consistently.
   * @param files - Array of scanned files to analyze for duplicates
   * @returns Dedupe result containing groups of duplicates and metadata about the analysis
   */
  async findDuplicates(files: IScannedFile[]): Promise<IDedupeResult> {
    const strategyExecutions: IStrategyExecution[] = [];
    const strategiesUsed: string[] = [];

    for (const strategy of this.strategies) {
      const candidates = await this.executeStrategy(strategy, files);
      if (candidates.length === 0) {
        continue;
      }

      strategiesUsed.push(strategy.name);
      strategyExecutions.push({
        strategy: strategy.name,
        keysByPath: new Map(
          candidates.map(candidate => [candidate.file.originalPath, candidate.key])
        )
      });
    }

    const groups = this.groupCandidates(files, strategyExecutions);

    return {
      groups,
      totalFiles: files.length,
      totalDuplicates: groups.reduce((sum, group) => sum + group.files.length, 0),
      strategiesUsed: [...strategiesUsed].sort((a, b) => a.localeCompare(b))
    };
  }

  /**
   * Applies the configured action to duplicate groups.
   * Currently supports SKIP, REPORT, and REPLACE actions.
   * Async for future extensibility (e.g., REPLACE action may need file operations).
   * @param result - Dedupe result containing duplicate groups to process
   * @param action - Action to apply to the duplicate groups (SKIP, REPORT, or REPLACE)
   * @returns Dedupe outcome with details about the action applied
   * @throws {Error} Thrown when an unsupported dedupe action is requested.
   */
  // eslint-disable-next-line @typescript-eslint/require-await
  async applyAction(result: IDedupeResult, action: DedupeAction): Promise<IDedupeOutcome> {
    switch (action) {
      case DedupeAction.SKIP:
        return this.applySkipAction(result);
      case DedupeAction.REPORT:
        return this.applyReportAction(result);
      case DedupeAction.REPLACE:
        return this.applyReplaceAction(result);
      default:
        throw new Error(`Unsupported dedupe action: ${String(action)}`);
    }
  }

  /**
   * Executes a single strategy on all files and returns candidates.
   * Only processes files supported by the strategy and filters out null keys.
   * @param strategy - Deduplication strategy to execute
   * @param files - Array of scanned files to process with the strategy
   * @returns Array of dedupe candidates generated by the strategy
   */
  private async executeStrategy(
    strategy: IDedupeStrategy,
    files: IScannedFile[]
  ): Promise<IDedupeCandidate[]> {
    const candidates: IDedupeCandidate[] = [];

    for (const file of files) {
      if (!strategy.supports(file)) {
        continue;
      }

      const key = await strategy.getKey(file);
      if (key !== null) {
        candidates.push({
          file,
          key,
          strategy: strategy.name
        });
      }
    }

    return candidates;
  }

  /**
   * Groups files by pairwise duplicate relationships derived from configured strategies.
   * @param files - Files being analyzed for duplicates
   * @param strategyExecutions - Strategy outputs keyed by file path
   * @returns Array of duplicate groups with multiple files per group
   */
  private groupCandidates(
    files: IScannedFile[],
    strategyExecutions: readonly IStrategyExecution[]
  ): IDuplicateGroup[] {
    if (files.length < 2 || strategyExecutions.length === 0) {
      return [];
    }

    const parents = files.map((_, index) => index);
    const pairMatches = new Map<string, readonly IStrategyMatch[]>();

    for (let leftIndex = 0; leftIndex < files.length - 1; leftIndex++) {
      for (let rightIndex = leftIndex + 1; rightIndex < files.length; rightIndex++) {
        const matches = this.findPairMatches(
          files[leftIndex].originalPath,
          files[rightIndex].originalPath,
          strategyExecutions
        );

        if (!this.isDuplicatePair(matches.matched, matches.applicableStrategies)) {
          continue;
        }

        this.union(parents, leftIndex, rightIndex);
        pairMatches.set(this.getPairId(leftIndex, rightIndex), matches.matched);
      }
    }

    return this.buildGroups(files, parents, pairMatches);
  }

  /**
   * Finds matching strategy keys for a pair of files.
   * @param leftPath - First file path
   * @param rightPath - Second file path
   * @param strategyExecutions - Strategy outputs keyed by file path
   * @returns Applicable strategy count and matching strategies
   */
  private findPairMatches(
    leftPath: string,
    rightPath: string,
    strategyExecutions: readonly IStrategyExecution[]
  ): {
    applicableStrategies: number;
    matched: readonly IStrategyMatch[];
  } {
    const matched: IStrategyMatch[] = [];
    let applicableStrategies = 0;

    for (const execution of strategyExecutions) {
      const leftKey = execution.keysByPath.get(leftPath);
      const rightKey = execution.keysByPath.get(rightPath);

      if (leftKey === undefined || rightKey === undefined) {
        continue;
      }

      applicableStrategies += 1;
      if (leftKey === rightKey) {
        matched.push({ strategy: execution.strategy, key: leftKey });
      }
    }

    return { applicableStrategies, matched };
  }

  /**
   * Determines whether a pair is duplicate under the configured composition mode.
   * @param matchedStrategies - Strategies whose keys matched for the pair
   * @param applicableStrategies - Enabled strategies that produced keys for both files
   * @returns True when the pair should be treated as duplicate
   */
  private isDuplicatePair(
    matchedStrategies: readonly IStrategyMatch[],
    applicableStrategies: number
  ): boolean {
    if (this.mode === DedupeMode.ALL) {
      return applicableStrategies > 0 && matchedStrategies.length === applicableStrategies;
    }

    return matchedStrategies.length > 0;
  }

  /**
   * Builds duplicate groups from the connected duplicate pairs.
   * @param files - Files being analyzed for duplicates
   * @param parents - Disjoint-set parent indices for each file
   * @param pairMatches - Matching strategies for each duplicate pair
   * @returns Array of duplicate groups
   */
  private buildGroups(
    files: IScannedFile[],
    parents: number[],
    pairMatches: ReadonlyMap<string, readonly IStrategyMatch[]>
  ): IDuplicateGroup[] {
    const groupedIndexes = new Map<number, number[]>();

    files.forEach((_, index) => {
      const root = this.find(parents, index);
      const group = groupedIndexes.get(root) ?? [];
      group.push(index);
      groupedIndexes.set(root, group);
    });

    const groups: IDuplicateGroup[] = [];
    for (const indexes of groupedIndexes.values()) {
      if (indexes.length < 2) {
        continue;
      }

      const groupFiles = indexes.map(index => files[index]);
      const matchMetadata = this.collectGroupMatches(indexes, pairMatches);
      const firstMatch = matchMetadata[0];
      const strategies = [...new Set(matchMetadata.map(match => match.strategy))];

      groups.push({
        key: firstMatch?.key ?? groupFiles[0].originalPath,
        strategy: strategies.join(','),
        strategies,
        files: groupFiles,
        primary: groupFiles[0]
      });
    }

    return groups;
  }

  /**
   * Collects all matching strategies contributing to a duplicate group.
   * @param indexes - File indexes in the duplicate group
   * @param pairMatches - Matching strategies for each duplicate pair
   * @returns Strategy match metadata for the group
   */
  private collectGroupMatches(
    indexes: readonly number[],
    pairMatches: ReadonlyMap<string, readonly IStrategyMatch[]>
  ): IStrategyMatch[] {
    const matches: IStrategyMatch[] = [];

    for (let leftIndex = 0; leftIndex < indexes.length - 1; leftIndex++) {
      for (let rightIndex = leftIndex + 1; rightIndex < indexes.length; rightIndex++) {
        const pair = pairMatches.get(this.getPairId(indexes[leftIndex], indexes[rightIndex]));
        if (pair) {
          matches.push(...pair);
        }
      }
    }

    return matches;
  }

  /**
   * Finds the representative index for the disjoint-set structure.
   * @param parents - Parent pointers for each file index
   * @param index - Index to resolve
   * @returns Representative index for the set
   */
  private find(parents: number[], index: number): number {
    if (parents[index] !== index) {
      parents[index] = this.find(parents, parents[index]);
    }

    return parents[index];
  }

  /**
   * Merges two duplicate sets in the disjoint-set structure.
   * @param parents - Parent pointers for each file index
   * @param leftIndex - First file index
   * @param rightIndex - Second file index
   */
  private union(parents: number[], leftIndex: number, rightIndex: number): void {
    const leftRoot = this.find(parents, leftIndex);
    const rightRoot = this.find(parents, rightIndex);

    if (leftRoot === rightRoot) {
      return;
    }

    parents[rightRoot] = leftRoot;
  }

  /**
   * Creates a stable map key for a pair of file indexes.
   * @param leftIndex - First file index
   * @param rightIndex - Second file index
   * @returns Stable pair identifier
   */
  private getPairId(leftIndex: number, rightIndex: number): string {
    return `${Math.min(leftIndex, rightIndex)}:${Math.max(leftIndex, rightIndex)}`;
  }

  /**
   * Applies SKIP action - marks duplicates for removal from operation queue.
   * Keeps the primary file and skips all duplicate files in each group.
   * @param result - Dedupe result containing duplicate groups to process
   * @returns Dedupe outcome with skipped duplicate files
   */
  private applySkipAction(result: IDedupeResult): IDedupeOutcome {
    const skipped: IScannedFile[] = [];
    for (const group of result.groups) {
      for (let i = 1; i < group.files.length; i++) {
        skipped.push(group.files[i]);
      }
    }

    return {
      action: DedupeAction.SKIP,
      skipped,
      replaced: [],
      reported: [],
      errors: []
    };
  }

  /**
   * Applies REPORT action - generates report without modifying operations.
   * Returns all duplicate groups for reporting purposes.
   * @param result - Dedupe result containing duplicate groups to report
   * @returns Dedupe outcome with all duplicate groups reported
   */
  private applyReportAction(result: IDedupeResult): IDedupeOutcome {
    return {
      action: DedupeAction.REPORT,
      skipped: [],
      replaced: [],
      reported: result.groups,
      errors: []
    };
  }

  /**
   * Applies REPLACE action - marks duplicates that should be removed before organization.
   * Keeps the primary file in each group and returns all remaining files as replacements.
   * @param result - Dedupe result containing duplicate groups to process
   * @returns Dedupe outcome with duplicate files marked for replacement
   */
  private applyReplaceAction(result: IDedupeResult): IDedupeOutcome {
    const replaced: IScannedFile[] = [];
    for (const group of result.groups) {
      for (let i = 1; i < group.files.length; i++) {
        replaced.push(group.files[i]);
      }
    }

    return {
      action: DedupeAction.REPLACE,
      skipped: [],
      replaced,
      reported: [],
      errors: []
    };
  }
}
