import { IScannedFile } from '../scanner/interfaces';

import {
  buildStrategyExecution,
  getSuccessfulCandidates,
  getSuccessfulExecutions,
  getSupportedFiles,
  type IStrategyExecution
} from './dedupe-analysis.helpers';
import type { IDedupeStrategy } from './interfaces';
import type { IDedupeCandidate } from './types';

/**
 * Creates a candidate for one file and strategy when a key is available.
 * @param strategy - Deduplication strategy to execute.
 * @param file - File being evaluated.
 * @returns Dedupe candidate or null when no key was produced.
 */
export async function createCandidate(
  strategy: Readonly<IDedupeStrategy>,
  file: Readonly<IScannedFile>
): Promise<IDedupeCandidate | null> {
  const key = await strategy.getKey(file);
  return key === null ? null : { file, key, strategy: strategy.name };
}

/**
 * Creates one candidate promise for a supported file.
 * @param strategy - Deduplication strategy to execute.
 * @param file - File being evaluated.
 * @returns Candidate promise.
 */
function createCandidatePromise(
  strategy: Readonly<IDedupeStrategy>,
  file: Readonly<IScannedFile>
): Promise<IDedupeCandidate | null> {
  return createCandidate(strategy, file);
}

/**
 * Creates candidate promises for each supported file.
 * @param strategy - Deduplication strategy to execute.
 * @param supportedFiles - Files supported by the strategy.
 * @returns Candidate promises.
 */
export function createCandidatePromises(
  strategy: Readonly<IDedupeStrategy>,
  supportedFiles: readonly IScannedFile[]
): readonly Promise<IDedupeCandidate | null>[] {
  return supportedFiles.map(createCandidatePromise.bind(undefined, strategy));
}

/**
 * Creates one strategy execution promise.
 * @param files - Files to evaluate.
 * @param strategy - Strategy being executed.
 * @returns Strategy execution promise.
 */
function createStrategyExecutionPromise(
  files: readonly IScannedFile[],
  strategy: Readonly<IDedupeStrategy>
): Promise<IStrategyExecution | null> {
  return executeSingleStrategy(strategy, files);
}

/**
 * Creates strategy execution promises for parallel evaluation.
 * @param strategies - Dedupe strategies to execute.
 * @param files - Scanned files to evaluate.
 * @returns Strategy execution promises.
 */
export function createStrategyExecutionPromises(
  strategies: readonly IDedupeStrategy[],
  files: readonly IScannedFile[]
): readonly Promise<IStrategyExecution | null>[] {
  return strategies.map(createStrategyExecutionPromise.bind(undefined, files));
}

/**
 * Executes one strategy and converts its candidates into keyed lookup data.
 * @param strategy - Deduplication strategy to execute.
 * @param files - Files to process with the strategy.
 * @returns Strategy execution metadata or null when no candidates were produced.
 */
export async function executeSingleStrategy(
  strategy: Readonly<IDedupeStrategy>,
  files: readonly IScannedFile[]
): Promise<IStrategyExecution | null> {
  const candidates = await executeStrategy(strategy, files);
  return candidates.length === 0 ? null : buildStrategyExecution(strategy.name, candidates);
}

/**
 * Executes strategies and returns successful keyed strategy outputs.
 * @param strategies - Dedupe strategies to execute.
 * @param files - Files being analyzed for duplicates.
 * @returns Successful strategy executions.
 */
export async function executeStrategies(
  strategies: readonly IDedupeStrategy[],
  files: readonly IScannedFile[]
): Promise<readonly IStrategyExecution[]> {
  const executions = await Promise.all(createStrategyExecutionPromises(strategies, files));
  return getSuccessfulExecutions(executions);
}

/**
 * Executes one strategy against supported files in parallel.
 * @param strategy - Deduplication strategy to execute.
 * @param files - Files to process with the strategy.
 * @returns Dedupe candidates generated by the strategy.
 */
export async function executeStrategy(
  strategy: Readonly<IDedupeStrategy>,
  files: readonly IScannedFile[]
): Promise<IDedupeCandidate[]> {
  const supportedFiles = getSupportedFiles(strategy, files);
  const candidateResults = await Promise.all(createCandidatePromises(strategy, supportedFiles));
  return getSuccessfulCandidates(candidateResults);
}
