import * as dedupe from './index';

describe('dedupe index exports', () => {
  it('should expose dedupe services, hashers, metadata, strategies, and enums', () => {
    expect(dedupe.DedupeReportWriter).toBeDefined();
    expect(dedupe.DedupeService).toBeDefined();
    expect(dedupe.createCandidate).toBeDefined();
    expect(dedupe.createCandidatePromises).toBeDefined();
    expect(dedupe.createStrategyExecutionPromises).toBeDefined();
    expect(dedupe.createDuplicatePairEvaluation).toBeDefined();
    expect(dedupe.createDuplicatePairEvaluations).toBeDefined();
    expect(dedupe.createFileIndexesByPath).toBeDefined();
    expect(dedupe.createMatchedPathPairMap).toBeDefined();
    expect(dedupe.countApplicableStrategies).toBeDefined();
    expect(dedupe.executeSingleStrategy).toBeDefined();
    expect(dedupe.executeStrategies).toBeDefined();
    expect(dedupe.executeStrategy).toBeDefined();
    expect(dedupe.findPairMatches).toBeDefined();
    expect(dedupe.groupAllModeCandidates).toBeDefined();
    expect(dedupe.groupCandidates).toBeDefined();
    expect(dedupe.groupAnyModeCandidates).toBeDefined();
    expect(dedupe.hasGroupableInput).toBeDefined();
    expect(dedupe.isDuplicateGroup).toBeDefined();
    expect(dedupe.isDuplicatePair).toBeDefined();
    expect(dedupe.isDuplicatePairEvaluation).toBeDefined();
    expect(dedupe.resolvePathPairIndexes).toBeDefined();
    expect(dedupe.shouldCreateDuplicatePairEvaluation).toBeDefined();
    expect(dedupe.toFileIndexEntry).toBeDefined();
    expect(dedupe.toDuplicatePairEvaluation).toBeDefined();
    expect(dedupe.toIndexPair).toBeDefined();
    expect(dedupe.unionParents).toBeDefined();
    expect(dedupe.Sha256Hasher).toBeDefined();
    expect(dedupe.MetadataExtractor).toBeDefined();
    expect(dedupe.ExifStrategy).toBeDefined();
    expect(dedupe.FileAttributesStrategy).toBeDefined();
    expect(dedupe.FilePropertiesStrategy).toBeDefined();
    expect(dedupe.ImageDimensionsStrategy).toBeDefined();
    expect(dedupe.NameStrategy).toBeDefined();
    expect(dedupe.Sha256Strategy).toBeDefined();
    expect(dedupe.SizeStrategy).toBeDefined();
    expect(dedupe.DedupeAction).toBeDefined();
    expect(dedupe.DedupeMode).toBeDefined();
  });
});
