export * from './cleaner/index.js';
export {
  addAutoConfigOption,
  addConfigOption,
  addDirectoryArgument,
  addLogLevelOption,
  buildDedupeActionContext,
  CleanHandler,
  COMMAND_MESSAGES,
  ConfigService,
  ConfigValidateHandler,
  createCommandAction,
  createCliActionMethodDecorator,
  createCommandMiddlewareDecorator,
  createCommandContextBase,
  createCommandMethodDecorator,
  createMethodDecorator,
  createWrappedCliActionDescriptor,
  createWrappedCliActionMethodDecorator,
  createWrappedMethodDecorator,
  createWrappedMethodDescriptor,
  createWrappedCommandMethodDecorator,
  createDedupeConfigOverrides,
  createDirectoryCommandAction,
  createMappedCommandContextBase,
  createReportWrites,
  createRootHandlers,
  createRootCommand,
  createRootServices,
  createRootWorkflows,
  createWrappedDescriptor,
  DedupeHandler,
  DedupePreset,
  DedupeRuntime,
  DedupeWorkflow,
  deleteFilePaths,
  DirectoryValidator,
  getDefaultReportPath,
  getOriginalPath,
  HandleCliActionErrors,
  HandleCommandErrors,
  handleReplacedDuplicates,
  handleSkippedDuplicates,
  InitHandler,
  invokeCliAction,
  invokeMethod,
  invokeCommand,
  isCliActionExecution,
  isCommandExecution,
  isCommandResult,
  logAutoDiscoveredConfig,
  ManifestService,
  normalizeDedupeCommandOptions,
  OrganizeDedupeService,
  OrganizeHandler,
  OrganizeWorkflow,
  quarantineFilePaths,
  registerConfigCommandGroup,
  registerFilesCommandGroup,
  resolveAction,
  resolveDedupeConfig,
  resolvePreset,
  resolveQuarantinePath,
  resolveReportPaths,
  resolveStrategyPreset,
  RevertHandler,
  runCommandResult,
  ScanHandler,
  ScanWorkflow,
  shouldDeleteDuplicates,
  toDeleteError,
  validateReplaceSafety,
  WatchHandler,
  WithAutoConfigDiscovery,
  WithCliAutoConfigDiscovery,
  WithCommandAudit,
  WithCommandTelemetry,
  CLI_CONSTANTS,
  ConfigFileFormat,
  ExitCode,
  type CommandMiddleware,
  type CommandExecution,
  type CliActionExecution,
  type IAutoConfigContext,
  type ICliActionExecutionRef,
  type IDedupeActionContext,
  type IDedupeCommandContext,
  type IDedupeCommandInput,
  type IDedupeContextBuildParams,
  type IDedupeWorkflowContext,
  type IDedupeWorkflowResult,
  type IDeleteSafetyContext,
  type IFilePathSource,
  type IMethodExecutionRef,
  type ICommandExecutionRef,
  type IOrganizeWorkflow,
  type IOrganizeWorkflowContext,
  type IReportPaths,
  type IRootHandlers,
  type IRootServices,
  type IRootWorkflows,
  type IScanWorkflowContext,
  type MethodExecution
} from './cli/index.js';
export type {
  ICleanCommandOptions,
  ICleanerService,
  ICleanHandler,
  ICommandContext,
  ICommandHandler,
  ICommandResult,
  IConfigService,
  IConfigValidateHandler,
  IConfigValidateOptions,
  IDedupeCommandOptions,
  IDedupeHandler,
  IDedupeReportService,
  IDirectoryValidator,
  IInitHandler,
  IInitOptions,
  IManifestService,
  IOrganizeHandler,
  IOrganizeOptions,
  IRevertCommandOptions,
  IRevertHandler,
  IScanHandler,
  IScanOptions,
  IWatchCommandOptions,
  IWatchHandler
} from './cli/interfaces.js';
export * from './config/index.js';
export * from './constants/index.js';
export * from './dedupe/index.js';
export * from './errors/index.js';
export * from './logger/index.js';
export * from './organizer/index.js';
export * from './scanner/index.js';
export * from './types/index.js';
export * from './utils/index.js';
